$(document).ready(function(){
	$(".all").click(function(){
		$(".rtt").fadeIn("fast");
		$(".htt").fadeIn("fast");
		$(".ecc").fadeIn("fast");
		$(".arr").fadeIn("fast");
		$(".eaa").fadeIn("fast");
	})
	$(".rt").click(function(){
		$(".rtt").fadeIn("fast");
		$(".htt").fadeOut("fast");
		$(".ecc").fadeOut("fast");
		$(".arr").fadeOut("fast");
		$(".eaa").fadeOut("fast");
	})
	$(".ht").click(function(){
		$(".rtt").fadeOut("fast");
		$(".htt").fadeIn("fast");
		$(".ecc").fadeOut("fast");
		$(".arr").fadeOut("fast");
		$(".eaa").fadeOut("fast");
	})
	$(".ec").click(function(){
		$(".rtt").fadeOut("fast");
		$(".htt").fadeOut("fast");
		$(".ecc").fadeIn("fast");
		$(".arr").fadeOut("fast");
		$(".eaa").fadeOut("fast");
	})
	$(".ar").click(function(){
		$(".rtt").fadeOut("fast");
		$(".htt").fadeOut("fast");
		$(".ecc").fadeOut("fast");
		$(".arr").fadeIn("fast");
		$(".eaa").fadeOut("fast");
	})
	$(".ea").click(function(){
		$(".rtt").fadeOut("fast");
		$(".htt").fadeOut("fast");
		$(".ecc").fadeOut("fast");
		$(".arr").fadeOut("fast");
		$(".eaa").fadeIn("fast");
	})
})